### PR TITLE
feat(shared images galleries): add amd64 and arm64 galleries

### PR DESCRIPTION
**Pull request by smerle33**
add galleries for amd64 and arm64 for windows also as it's now mandatory to have the architecture within the gallery name for our packer to upload images.
windows ARM64 is not used yet.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by dduportal — COMMENTED** [review]
To be verified, but I don't believe there are Windows Server ARM64 images.

**Comment by smerle33** [comment]
> To be verified, but I don't believe there are Windows Server ARM64 images.

I was more thinking on more folders in case we will use them WDYT ? ... I also changed all region to us-east 

Plan: 13 to add, 0 to change, 1 to destroy.

**Comment by dduportal** [comment]
> I was more thinking on more folders in case we will use them WDYT?

We don't need them, so better not creating them empty. If we need them, it'll be easy to add them

**Comment by smerle33** [comment]
> > I also changed all region to us-east
> 
> What is the impact ?

FWIT none ...

**Pull request merged**
