### PR TITLE
WIP: Packer for ci.jenkins.io

### PR DESCRIPTION
**Pull request by rtyler**

### CODE REVIEW

**Comment by rtyler** [comment]
I had worked on this ages ago, and then lost track of it due to time

**Comment by olblak** [comment]
:tada:  Awesome, I recently started looking after azure images build with packer :) I review this when I hame some time

**Comment by rtyler** [comment]
This may not be necessary with the Azure Container Instances support I'm experimenting with

**Comment by olblak** [comment]
I think it's still useful to have a machine with docker daemon to build and test docker images

**Pull request closed without merging**
