### PR TITLE
feat(ldap,repo.azure) add new managed disk for AKS PV to support `arm64` migration

### PR DESCRIPTION
**Pull request by dduportal**
Related to https://github.com/jenkins-infra/helpdesk/issues/3837#issuecomment-2210532769 and https://github.com/jenkins-infra/helpdesk/issues/3837#issuecomment-2210593052

This PR creates the 3 required sets of disk/PV/PV used for ACP and LDAP with the following specific settings:

- Use ZRS to allow moving across AZs
- Decrease disk type from (overpriced) Premium to Standard SSD
- Adapt disk size to their real production usage AND pricing model
    - Always less than 80 % usage to keep good performances
    - Use as much as available space as provided by Azure disks

Note: this PR requires #774 to be merged

### CODE REVIEW

**Review by dduportal — COMMENTED** [review]
`Plan: 15 to add, 0 to change, 0 to destroy.`

- 2 new RGs
- 3 new disks
- 3 new PVs
- 3 new PVCs
- 2 new Azure Roles
- 2 new Azure Role assignements

**Comment by dduportal** [comment]
Back to draft: I have to rework the ACP PV/PVCs.

As per https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd#pv_to_statefulset, the PVC are handled by the StatefulSet.
It requires to set up the proper naming for PVs though.

**Comment by dduportal** [comment]
> Back to draft: I have to rework the ACP PV/PVCs.
> 
> As per https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd#pv_to_statefulset, the PVC are handled by the StatefulSet. It requires to set up the proper naming for PVs though.

As per https://github.com/jenkins-infra/helm-charts/pull/1205, we expect the 2 ACP PVCs to be named:

- `data-artifact-caching-proxy-0`
- And `data-artifact-caching-proxy-1`

**Review by dduportal — COMMENTED** [review]
`Plan: 13 to add, 0 to change, 0 to destroy.` => 2 PVCs removed so 👍

**Review by smerle33 — APPROVED** [review]
🚀

**Pull request merged**
