### PR TITLE
fix: restrict access to `archives` storage account

### PR DESCRIPTION
**Pull request by lemeurherve**
can't access containers otherwise

### CODE REVIEW

**Review by dduportal — CHANGES_REQUESTED** [review]
Not sure we want this. We want items to be private, which would require setting carefully the permissions

**Review by timja — DISMISSED** [review]
I assume this is temporary until the TODO is solved:

> TODO: set to false and add a network rule allowing only the VPN as soon as this one has been deployed so we can access containers in the mean time.

**Comment by lemeurherve** [comment]
@timja indeed. I went ahead and added network rules, allowing only a set of our IPs and the subnet where temp-privatek8s is located.

Note: I had to add a sevice endpoint on this subnet virtual network to avoid a NetworkAclsValidationFailure:

image

**Review by dduportal — APPROVED** [review]
`No changes. Your infrastructure matches the configuration.` => LGTM

**Pull request merged**
